### PR TITLE
updated navbar to fix bug

### LINKED ISSUE #173: Bug Report - Replacing sign in option with the username of the User in navbar after log in.
Currently even after the user signs in the user still sees the sign in option, which badly affects the user experience.
So to enhance user experience the sign in option is replaced with the user name once user logs in.
**Currently:**

Image

**Updated:**

Image

To resolve the issue, i have replaced the sign in option with the user name stored in the userinfo object.

@Heisen47 Kindly review the issue, and assign it under HacktoberFest'25.

### PR DESCRIPTION
**Pull request by DARSHITSHAH-2906**
Closes #173 

Currently even after the user signs in the user still sees the sign in option, which badly affects the user experience.
So to enhance user experience the sign in option is replaced with the user name once user logs in.
**Currently:**

Image

**Updated:**

Image

To resolve the issue, i have replaced the sign in option with the user name stored in the userinfo object.

### CODE REVIEW

File: components/Navbar.tsx [hunk 1]
```diff
@@ -193,9 +193,9 @@ const Navbar = () => {
   }, []);
 
   const navItems = [
-    { label: "Home", href: "#home"},
-    { label: "About", href: "#about"},
-    { label: "Features", href: "#features"},
+    { label: "Home", href: "/" },
```
Comment (Heisen47) [inline components/Navbar.tsx:196]: make this href = "#home"

**Comment by Heisen47** [comment]
@DARSHITSHAH-2906  , do the above change i requested and let me know .

**Comment by DARSHITSHAH-2906** [comment]
Updated the base branch to dev.
@Heisen47 kindly review , and inform if any suggestion.

**Review by Heisen47 — APPROVED** [review]
